// 13/12/2025 AI-Tag
// This was created with the help of Assistant, a Unity Artificial Intelligence product.

using System;
using UnityEditor;
using UnityEngine;
using System.Collections.Generic;
using Unity.VisualScripting;

[CreateAssetMenu(fileName = "TrainerConfig", menuName = "Battle/TrainerConfig")]
public class TrainerConfig : ScriptableObject
{
    public string trainerName;
    public Trainer_Class trainerClass;
    public MusicList.Music_Battle battleMusic;
    public MusicList.Music_Encounter encounterMusic;
    public Trainer_Sprites trainerPicture;
    public AIFlags aiFlags;
    public List<Monster> party;
}

[System.Flags]
public enum AIFlags
{
    CheckBadMove = 1 << 0,
    CheckViability = 1 << 1,
    TryToFaint = 1 << 2,
}

[System.Serializable]
public class TrainerMon
{
    public Species species;
    public string nickname;
    public int level;
    public List<string> moves;
    public Dictionary<string, int> skills;
}


    /*OZAN = ("Resources/trainers/ozan.png");
    RAPTOR = ("Resources/trainers/raptor.png");
    DEMONHEADGE = ("Resources/trainers/demonheadge.png");

    MUS_ROUTE_DESERT = ("Resources/musc/mus_route_desert.mid");*/

public enum Trainer_Sprites
{
    NONE,
    PROTAGANIST_M,
    PROTAGANIST_F,
    HAM_GRUNT_F,
    HAM_GRUNT_M,
    HAM_BABE,
    HAM_PATTY,
    HAM_JOHANHUS,
    HAM_SIGMUND,
    BABE_POSTGAME,
    PATTY_POSTGAME,
    SIGMUND_POSTGAME,
    ZANIK_E4,
    ZANIK_CAVES,
    ZANIK_HAM,
    A_NUB_TOT,
    ARIANE,
    COUNT_DRAYNOR,
    DURIAL321,
    KATRINE,
    MAGGIE,
    MEG,
    MITHRILMAN,
    OZAN,
    RAPTOR,
    SIGMUND,
    SIR_OWEN,
    STRAVEN,
    XEINA,
    ZANIK,
    BARROWS_VERAC,
    DUKE_HORACIO,
    GUNTHOR,
    KING_ROALD,
    PRINCE_ALI,
    SIR_AMIK_VARZE,
    TZHAAR,
    VANNAKA,
    WISE_OLD_MAN_CHAMPION,
    CANADA_GRRL,
    PREZLEEK,
    WILLMISSIT,
    DEMONHEADGE,
    GENTLESHEN,
    HYPERSTAN,
    JITTERBUG,
    LOPENDEBANK,
    ORCHY,
    SUDO_BASH,
    BARBARIAN_DUO,
    BARBARIAN_F,
    BARBARIAN_M,
    BLACK_KNIGHT_F,
    BLACK_KNIGHT_M,
    BOT_DRAGON_SLAYER,
    BOT_MINER,
    BOT_WOODCUTTING,
    DND,
    DWARF_M,
    FARMER,
    FISHER,
    GOBLIN,
    GOEBIE,
    GUARD_ALKHAIRD,
    GUARD_ALKHAIRD_DUO,
    GUARD_FALADOR,
    GUARD_KHAZARD,
    GUARD_VARROCK,
    GUTHIX_WIZARD,
    HAIRDRESSER,
    HUNTER_F,
    HUNTER_M,
    IRONMAN,
    JMOD_F,
    JMOD_M,
    MERCHANT,
    MILLER,
    MINER,
    MONK,
    MUGGER,
    NOOB_DEFAULT,
    NOOB_RUNE,
    PIRATE,
    PK_DH,
    PK_RUSHER,
    RSMV_F,
    SAILOR,
    SCAMMER,
    SCAMMER_AND_VICTIM,
    SKELETON,
    SKILLER,
    SLAYER,
    SMITH,
    SUMMONER,
    TRIBESMAN,
    WHITE_KNIGHT_F,
    WHITE_KNIGHT_M,
    WIZARD_F,
    WIZARD_M,
    WOODCUTTER,
    WOODCUTTER_ALT,
    COOK,
    COOK_FM_DUO,
    LUKIEN,
    FIREMAKING,
    PK_DUO,
    ARCHAEOLOGIST,
    RSMV_DUO,
    RSMV_M,
    AHRIM_OSRS,
    DHAROK_OSRS,
    TORAG_OSRS,
    KARIL_OSRS,
    GUTHAN_OSRS,
    VERAC_OSRS,
    WIZARD_DARK,
    DIVINATION,
    GERTRUDE,
    GRACEFUL,
    GUARD_DRAYNOR,
    QUESTER,
    SOFFANQUO,
    BARROWS_RS3_GUTHAN,
    BARROWS_RS3_KARIL,
    CHASE,
    DRAGON_ARMOUR,
    DUO_DRAGON_RANGER,
    DUO_MAGE_LIGHT,
    DUO_MAGE_RUNECRAFT,
    FIRE_GIANT,
    GRACEFUL_2,
    HILL_GIANT,
    JOE,
    LADY_KELI,
    MAGE_MYSTIC,
    METEOR,
    MOSS_GIANT,
    NECROMANCER,
    PIPPINSMITH,
    RAMOKEE,
    RANGER_ROBIN,
    RUNECRAFTER,
    THOK,
    VOIDKNIGHT_1,
    VOIDKNIGHT_2,
    VOIDKNIGHT_3,
    VOIDKNIGHT_4,
    VOIDKNIGHT_5,
    WISEOLDMAN_1,
    WISEOLDMAN_2,
    WIZARD_ZAMORAK,
    HANS,
    HAZELMERE,
    SIR_TIFFY,
    MRKALIUS,
    TWISTED,
    THOK_GYMLEADER,
    WORLD_GUARDIAN,
    SANDWICH_LADY,
    GUARD_VARROCK_POSE,
    ZEMOUREGAL,
    LORD_DAQUARIUS,
    ELITE_BLACK_KNIGHT,
    ANGRENNOUILLE,
    GUARD_ALKHAIRD_ALT,
    PLAYER_BRONZE,
    PLAYER_IRON,
    PLAYER_STEEL,
    PLAYER_MITHRIL,
    PLAYER_ADAMANT,
    PLAYER_RUNE,
    STEELWOMAN,
    ADAMANTWOMAN,
    MALIGNIUS_MORTIFER,
    TZHAAR_KET,
    TZHAAR_KET_HD,
    TZHAAR_GA_AL,
    TOKHAAR,
    DUNGEONEERING_EDIMMU,
    DUNGEONEERING_RUSHER,
    DUNGEONEERING_FORGOTTEN_MAGE_LOW,
    DUNGEONEERING_FORGOTTEN_MAGE_MED,
    DUNGEONEERING_FORGOTTEN_MAGE_HIGH,
    DUNGEONEERING_FORGOTTEN_MAGE_CELESTIAL,
    DUNGEONEERING_FORGOTTEN_RANGER_LOW,
    DUNGEONEERING_FORGOTTEN_RANGER_MED,
    DUNGEONEERING_FORGOTTEN_RANGER_HIGH,
    DUNGEONEERING_FORGOTTEN_RANGER_SAGITTARIAN,
    DUNGEONEERING_FORGOTTEN_WARRIOR_LOW,
    DUNGEONEERING_FORGOTTEN_WARRIOR_MED,
    DUNGEONEERING_FORGOTTEN_WARRIOR_HIGH,
    DUNGEONEERING_FORGOTTEN_WARRIOR_PRIMAL,
}
public enum Trainer_Class
{
    NONE,
    NOOB,
    MILLER,
    GOBLIN,
    SKELETON,
    TZHAAR,
    GOEBIE,
    HAM_GRUNT,
    HAM_BOSS,
    WHITE_KNIGHT,
    BLACK_KNIGHT,
    WIZARD,
    WITCH,
    GUARD,
    JMOD,
    BOT,
    MERCHER,
    PKER,
    DWARF,
    MUGGER,
    SAILOR,
    PIRATE,
    BARBARIAN,
    IRONMAN,
    MITHRILMAN,
    SCAMMER,
    VICTIM,
    TRIBESMAN,
    RSMV,
    DnD,
    QUESTER,
    LOREHOUND,
    VAMPYRE,
    COUNT,
    DUKE,
    KING,
    PRINCE,
    CHIEFTAIN,
    UNKNOWN,
    WARRIOR,
    SIR,
    SKILLER,
    SLAYER,
    WOODCUTTER,
    SMITH,
    MINER,
    MONK,
    HUNTER,
    FIREMAKER,
    FARMER,
    SUMMONER,
    FISHER,
    POKESCAPER,
    SIGNATURE_HERO,
    PLAYER,
    BARROWS_BROTHER,
    LEGEND,
    CHEF,
    AGILE,
    DARK_WIZARD,
    DIVINER,
    DUO,
    ARCHAEOLOGIST,
    HILL_GIANT,
    MOSS_GIANT,
    FIRE_GIANT,
    HAM_ADMIN,
    NECROMANCER,
    RUNECRAFTER,
    WISE_OLD_MAN,
    JAILER,
    FORGOTTEN_WARRIOR,
    RANGER,
    SANDWICH,
    MELZAR,
    ZAMORAK_MONK,
    STRANGER,
    CHOOB,
    ZAMORAK_WIZARD,
    VOID_KNIGHT,
    SKINWEAVER,
    DG_RUSHER,
    FORGOTTEN_RANGER,
    FORGOTTEN_MAGE,
}


public static class MusicList
{
    public enum Music_Area
    {
        NONE,
        MUS_TITLESCREEN,
        MUS_BANK,
        MUS_GENERAL_STORE,
        MUS_PUB,
        MUS_CHURCH,
        MUS_GYM,
        MUS_FOREST_F2P,
        MUS_FOREST_P2P,
        MUS_CAVE_F2P,
        MUS_CAVE_P2P,
        MUS_SURFING,
        MUS_TERRORBIRD,
        MUS_LUMBRIDGE,
        MUS_DRAYNOR,
        MUS_WIZARDS_TOWER,
        MUS_PORT_SARIM,
        MUS_RIMMINGTON,
        MUS_FALADOR,
        MUS_VARROCK,
        MUS_ALKHARID,
        MUS_MUSA_POINT,
        MUS_BARBARIAN_VILLAGE,
        MUS_EDGEVILLE,
        MUS_ROUTE_LUMBRIDGE,
        MUS_ROUTE_PORT_SARIM,
        MUS_ROUTE_RIMMINGTON,
        MUS_ROUTE_ASGARNIA,
        MUS_ROUTE_MISTHALIN,
        MUS_ROUTE_DESERT,
        MUS_ROUTE_KARAMJA,
        MUS_ROUTE_WILDERNESS,
        MUS_VICTORY_ROAD,
        MUS_KOUREND_CATACOMBS,
        MUS_GODSLAYER,
        MUS_LUMBRIDGE_CASTLE,
        MUS_TZHAAR,
        MUS_ICE_MOUNTAIN,
        MUS_HAM_HIDEOUT,
        MUS_HAM_HIDEOUT_HIGH_ALERT,
        MUS_WISE_OLD_MAN_THEME,
    }

    public enum Music_Fanfare
    {
        NONE,
        MUS_GET_BADGE,
        MUS_GET_ITEM,
        MUS_LVL_UP,
        MUS_QUEST_COMPLETE,
        MUS_TRAINER_VICTORY,
    }

    public enum Music_Battle
    {
        NONE,
        MUS_VS_WILD_F2P,
        MUS_VS_WILD_P2P,
        MUS_VS_TRAINER_F2P,
        MUS_VS_TRAINER_P2P,
        MUS_VS_GYM,
        MUS_VS_HAM,
        MUS_VS_KNIGHTS,
        MUS_VS_ELITE4,
        MUS_VS_LEGENDARY,
        MUS_VS_CHAOS_ELEMENTAL,
        MUS_VS_POKESCAPERS,
        MUS_VS_DEMONHEADGE,
        MUS_VS_ORCHY,
        MUS_VS_CHAOS_TUNNELS,
        MUS_VS_WISE_OLD_MAN_RIVAL,
        MUS_VS_HAM_NEW,
        MUS_VS_HAM_ADMIN,
        MUS_VS_TZHAAR,
        MUS_VS_FROGEELMAN,
    }

    public enum Music_Encounter
    {
        NONE,
        ENCOUNTER_MUSIC_PKER,
        ENCOUNTER_MUSIC_HAM,
        ENCOUNTER_MUSIC_NOOB,
        ENCOUNTER_MUSIC_CHOOB,
        ENCOUNTER_MUSIC_SKILLER,
    }
}